import { Suspense } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getResources, getT, initServerI18next } from "next-i18next/server";
import { cn } from "@/lib/utils";
import { AuthProvider } from "@/providers/auth-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { QueryProvider } from "@/providers/query-provider";
import { Toaster } from "@/components/ui/sonner";
import "@/css/styles.css";
import { i18nConfig } from "@/i18n/i18n.config";
import { I18nNextProvider } from "@/providers/i18n-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

initServerI18next(i18nConfig);

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { i18n, lng } = await getT();
  const resources = getResources(i18n);

  return (
    <html className="h-full" lang={lng} suppressHydrationWarning>
      <body className={cn("text-base antialiased", inter.className)}>
        <QueryProvider>
          <AuthProvider>
            <ThemeProvider>
              <I18nNextProvider resources={resources} language={lng}>
                <Toaster />
                <Suspense>{children}</Suspense>
              </I18nNextProvider>
            </ThemeProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
