export const GITHUB_LANGUAGES = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C",
  "C++",
  "C#",
  "Go",
  "Rust",
  "Kotlin",
  "Swift",
  "PHP",
  "Ruby",
  "Dart",
  "Scala",
  "Shell",
  "PowerShell",
  "Haskell",
  "Elixir",
  "Clojure",
  "Objective-C",
  "Objective-C++",
  "MATLAB",
  "R",
  "Lua",
  "Groovy",
  "Assembly",
  "Vim Script",
  "F#",
  "OCaml",
  "Solidity",
  "Zig",
  "Crystal",
  "Nim",
  "Fortran",
  "COBOL",
];

export const DEFAULT_PAGINATION_STATE = { pageIndex: 0, pageSize: 10 };
export const DEFAULT_SORTING_STATE = [{ id: "watchers", desc: true }];
