name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      # 🔥 DB schema sync
      - name: Run Prisma Migrations
        run: npx prisma migrate deploy
        env:
         DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test --if-present

      - name: Build
        run: npm run build

      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}

      # 🔥 SENTRY RELEASE
      - name: Create Sentry release
        run: |
          npx @sentry/cli releases new nextjs-demo-app@${{ github.sha }}
          npx @sentry/cli releases set-commits nextjs-demo-app@${{ github.sha }} --auto
          npx @sentry/cli releases finalize nextjs-demo-app@${{ github.sha }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

      # 🔥 Upload sourcemaps
      - name: Upload Sentry sourcemaps
        run: |
          npx @sentry/cli sourcemaps upload .next --release nextjs-demo-app@${{ github.sha }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}